import React from 'react';
import { Inter } from 'next/font/google'
import { AntdRegistry } from '@ant-design/nextjs-registry';
import { ContentBlock } from '@/components/Content';
import { FooterBlock } from '@/components/Navigation/FooterBlock';
import { HeaderBlock } from '@/components/Navigation/HeaderBlock';
import { SiderBlock } from '@/components/Navigation/SiderBlock';

import { Layout } from 'antd';

export type MenuType = {
  title: string
  link: string
}

const items: MenuType[] = [
    {
      title: 'Todo List',
      link: '/todo'
    },
    {
      title: 'test glav',
      link: '/'
    }
]

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en">
      <body className={inter.className}>
        <AntdRegistry>
          <Layout>
            <SiderBlock items={items} />
            <Layout>
              <HeaderBlock />
              <ContentBlock >
                {children}
              </ContentBlock>
              <FooterBlock />
            </Layout>
          </Layout>
        </AntdRegistry>
      </body>
    </html>
  )

}